# GitHub Actions CI/CD pipeline: Build, Push, and Deploy Docker application to AWS EC2 via ECR

name: CI/CD - Build, Push to ECR & Deploy to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "docker-app/**"

    # Enables GitHub OIDC authentication with AWS (no static credentials required)
permissions:
  id-token: write # allows GitHub to generate OIDC token for AWS login
  contents: read # allows workflow to access your repo code

# these variables are used in the 'build image' step to provide value to the env vars.
env:
  ECR_REPOSITORY: my-app
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials using GitHub OIDC → IAM Role assumption
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::565393030819:role/Github-Actions-role
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Wait for ECR repository to exist
      #   run: |
      #     echo "Checking for ECR repository..."
      #     for i in $(seq 1 20); do
      #       if aws ecr describe-repositories --repository-names my-app --region us-east-2 2>/dev/null; then
      #         echo "ECR repository found — continuing"
      #         exit 0
      #       fi
      #       echo "Attempt $i/20 — ECR not ready yet, waiting 30 seconds..."
      #       sleep 30
      #     done
      #     echo "ECR repository not found after 10 minutes — exiting"
      #   exit 1

      # GitHub Actions assumes AWS IAM role using OIDC (no static AWS keys)
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build image - This step builds Docker image from the app code stored in "./docker-app" folder.
      # Reads the Dockerfile, downloads base image (nginx), runs each instruction in the dockerfile (COPY) and produces image
      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./docker-app

      # Tag image for ECR - use the values in the variables above to tag the image
      - name: Tag image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      # Push Docker image to Amazon ECR repository
      - name: Push image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      # Deploy via ssm
      - name: Deploy via SSM
        run: |
          aws ssm send-command \
              --targets "Key=tag:Name,Values=docker-ec2-server" \
              --document-name "AWS-RunShellScript" \
              --parameters 'commands=[
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}",
              "docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}",
              "docker container stop my-app || true",
              "docker container rm my-app || true",  
              "docker container run -d --name my-app -p 80:80 ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
              ]'
